"""Version-aware keyword diagnostics generated by OpenQC LSP Factory."""

from __future__ import annotations

import json
import os
import re
from pathlib import Path
from typing import Any

from .validator import Diagnostic

RULE_REMOVED_KEYWORD = "cp2k.version.removed_keyword"
RULE_DEPRECATED_KEYWORD = "cp2k.version.deprecated_keyword"
RULE_UNKNOWN_KEYWORD = "cp2k.version.unknown_keyword"

_KEYWORD_RE = re.compile(r"^(\s*)([A-Za-z][A-Za-z0-9_\-]*)\b(.*)$")
_SECTION_RE = re.compile(r"^\s*&(?P<name>[A-Za-z][A-Za-z0-9_\-]*)(?:\s+.*)?$", re.IGNORECASE)
_END_RE = re.compile(r"^\s*&END(?:\s+(?P<name>[A-Za-z][A-Za-z0-9_\-]*))?\b", re.IGNORECASE)
_FREE_FORM_SECTIONS = {
    "COORD",
    "COLLECTIVE",
    "CONSTRAINT_INFO",
    "FORCE",
    "MULTIPLE_UNIT_CELL",
    "SCALED",
    "SHELL_COORD",
    "VELOCITY",
}


def load_version_policy(path: str | Path) -> dict[str, Any]:
    """Load a version-policy JSON file produced by release-diff."""
    with Path(path).open(encoding="utf-8") as handle:
        policy = json.load(handle)
    if not isinstance(policy, dict):
        raise ValueError(f"version policy must be a JSON object: {path}")
    return policy


def lint_version_policy_from_env(text: str) -> list[Diagnostic]:
    """Run version-policy lint when CP2K_VERSION_POLICY points to a policy file."""
    policy_path = os.environ.get("CP2K_VERSION_POLICY")
    if not policy_path:
        return []
    path = Path(policy_path)
    if not path.exists():
        return [
            Diagnostic(
                severity="warning",
                source="cp2k-version-policy",
                code="cp2k.version.policy_missing",
                message=f"CP2K_VERSION_POLICY does not exist: {path}",
                line=0,
            )
        ]
    return lint_version_policy(text, load_version_policy(path))


def lint_version_policy(text: str, policy: dict[str, Any]) -> list[Diagnostic]:
    """Distinguish removed, deprecated, and unknown keywords for a CP2K version."""
    keywords = {
        str(item.get("name", "")).upper(): item
        for item in policy.get("keywords", [])
        if isinstance(item, dict) and item.get("name")
    }
    active = {name for name, item in keywords.items() if str(item.get("status", "active")).lower() == "active"}
    diagnostics: list[Diagnostic] = []
    section_stack: list[str] = []

    for line_no, line in enumerate(text.splitlines()):
        stripped = line.strip()
        if not stripped or stripped.startswith(("!", "#", "@")):
            continue
        end_match = _END_RE.match(line)
        if end_match:
            end_name = (end_match.group("name") or "").upper()
            if end_name and end_name in section_stack:
                while section_stack:
                    name = section_stack.pop()
                    if name == end_name:
                        break
            elif section_stack:
                section_stack.pop()
            continue
        section_match = _SECTION_RE.match(line)
        if section_match:
            section_stack.append(section_match.group("name").upper())
            continue
        if any(section in _FREE_FORM_SECTIONS for section in section_stack):
            continue
        match = _KEYWORD_RE.match(line)
        if not match:
            continue
        keyword = match.group(2).upper()
        item = keywords.get(keyword)
        if item is None:
            if active:
                diagnostics.append(
                    Diagnostic(
                        severity="warning",
                        source="cp2k-version-policy",
                        code=RULE_UNKNOWN_KEYWORD,
                        message=f"Keyword '{keyword}' is unknown in CP2K {policy.get('version', 'version policy')}.",
                        line=line_no,
                        column=match.start(2),
                    )
                )
            continue

        status = str(item.get("status", "active")).lower()
        replacement = str(item.get("replacement", "") or "")
        if status == "removed":
            diagnostics.append(
                Diagnostic(
                    severity="error",
                    source="cp2k-version-policy",
                    code=RULE_REMOVED_KEYWORD,
                    message=f"Keyword '{keyword}' was removed in CP2K {policy.get('version', 'this version')}.",
                    line=line_no,
                    column=match.start(2),
                    suggested_fix=_replacement_hint(keyword, replacement),
                )
            )
        elif status == "deprecated":
            diagnostics.append(
                Diagnostic(
                    severity="warning",
                    source="cp2k-version-policy",
                    code=RULE_DEPRECATED_KEYWORD,
                    message=f"Keyword '{keyword}' is deprecated in CP2K {policy.get('version', 'this version')}.",
                    line=line_no,
                    column=match.start(2),
                    suggested_fix=_replacement_hint(keyword, replacement),
                )
            )

    return diagnostics


def _replacement_hint(keyword: str, replacement: str) -> str | None:
    if not replacement:
        return None
    return f"Replace {keyword} with {replacement}."
